# Generated by Django 3.2.16 on 2023-01-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20230125_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='confirm_password',
        ),
    ]
